window.DS = {
  tarotMajor: [
    ["The Fool","A new beginning. Let go of caution, trust the journey.",["New opportunity near","Good time to take risks","Watch impulsiveness"]],
    ["The Magician","Tools in hand, everything is possible.",["Act decisively","Turn ideas into reality","High energy"]],
    ["The High Priestess","Call of intuition and inner wisdom.",["Pause and listen","Trust your gut","Answer lies within"]],
    ["The Empress","Abundance, nurture, feminine power.",["Harvest season","Being cared for / caring","Wealth and stability"]],
    ["The Emperor","Order, authority, control.",["Set the rules","Authority figure","Secure foundation"]],
    ["The Hierophant","Tradition, guidance, spiritual teacher.",["Follow the rules","Seek advice","Learning"]],
    ["The Lovers","Choice, love, union.",["Major decision","Relationship heats up","Values clash"]],
    ["The Chariot","Willpower, conquer challenges.",["Push through","Clear goal wins","Watch haste"]],
    ["Strength","Gentle power, inner courage.",["Stay calm","Gentleness wins","Patience"]],
    ["The Hermit","Solitude, reflection, seeking.",["Temporary retreat","Answers from within","Clarity after rest"]],
    ["Wheel of Fortune","Turning point, cycle shift.",["Opportunity arrives","Go with the flow","Cycles repeat"]],
    ["Justice","Karma, fairness, decision.",["Fair ruling","Effort pays off","Weigh carefully"]],
    ["The Hanged Man","New angle, gain through pause.",["Brief stall","Change perspective","Growth through sacrifice"]],
    ["Death","Endings birth new beginnings.",["Old chapter closes","Let go to grow","Transformation"]],
    ["Temperance","Balance, harmony, gradual progress.",["Slow down","Middle path","Steady toward goal"]],
    ["The Devil","Desire, bondage, obsession.",["Face your desires","Break free","See your chains"]],
    ["The Tower","Sudden change, breakthrough.",["Unexpected shake-up","Reset","Truth revealed"]],
    ["The Star","Hope, healing, guidance.",["Dark times end","Keep dreaming","Be sincere"]],
    ["The Moon","Confusion, illusion, subconscious.",["Truth is hazy","Beware fantasy","Check facts"]],
    ["The Sun","Success, vitality, life force.",["Great success","High energy","Time to celebrate"]],
    ["Judgement","Awakening, rebirth, calling.",["Old debts settled","Deserved answer","Clear calling"]],
    ["The World","Completion, achievement, fulfillment.",["Mission accomplished","Phase complete","Look further"]]
  ],
  zodiacs: [
    ["Rat","Water sign. Smart and observant. Supportive year, build connections.",["Good for networking","Steady income","Friends help"]],
    ["Ox","Earth sign. Steady and hardworking. Slow and steady wins.",["Deep skill","Keep grinding","Hidden chance"]],
    ["Tiger","Wood sign. Bold leader energy. Stay humble, soft over strong.",["Watch ego","Stable wins","Crisis = chance"]],
    ["Rabbit","Wood sign. Gentle and charming. Smooth year, love and work thrive.",["Popularity grows","Love blooms","People-facing"]],
    ["Dragon","Earth sign. Ambitious and impressive. Watch gossip, stay calm.",["Big plans OK","Avoid rivals","Quiet power"]],
    ["Snake","Fire sign. Strategic and deep. Build inner strength quietly.",["Calm year","Silent prep","H2 improves"]],
    ["Horse","Fire sign. Passionate and driven. Dynamic year, defend not attack.",["Watch travel","Stay grounded","Defense wins"]],
    ["Goat","Earth sign. Kind and considerate. Lucky triads, supportive people.",["Team up","Good money","Lucky year"]],
    ["Monkey","Metal sign. Clever and quick. Watch contracts and cooperation.",["Word skills","Brain work","Paper up front"]],
    ["Rooster","Metal sign. Direct and precise. Relationship and money move.",["Guard wealth","Autumn window","Grab chance"]],
    ["Dog","Earth sign. Loyal and honest. Guard money, be careful.",["No loans","Watch plenty","Move slowly"]],
    ["Pig","Water sign. Easygoing and lucky. Steady year, don't rush.",["Save money","Lucky by nature","Patience pays"]]
  ],
  stars: [
    ["Aries","Fire · Mars. Bold and direct, natural leader.",["Push now","Career leap","Watch impulse"]],
    ["Taurus","Earth · Venus. Steady and sensual, great endurance.",["Money climbs","Slow love","Treat yourself"]],
    ["Gemini","Air · Mercury. Quick and social, loves variety.",["Talk wins","Share ideas","Focus!"]],
    ["Cancer","Water · Moon. Emotional, nurturing, intuitive.",["Home wins","Stabilize","Self-care"]],
    ["Leo","Fire · Sun. Confident and warm, ruler energy.",["Career shine","Recognition","Watch pride"]],
    ["Virgo","Earth · Mercury. Precise and helpful, perfectionist.",["Details win","Polish work","Be gentle"]],
    ["Libra","Air · Venus. Balanced and social, aesthetic eye.",["People power","Partnership","Decide!"]],
    ["Scorpio","Water · Pluto/Mars. Deep and intense, sharp.",["Long game","Power moves","Let go"]],
    ["Sagittarius","Fire · Jupiter. Optimistic and free, lucky.",["Travel/learn","Luck flows","Big heart"]],
    ["Capricorn","Earth · Saturn. Disciplined and ambitious.",["Effort pays","Climb steady","Rest too"]],
    ["Aquarius","Air · Uranus. Independent and innovative.",["Ideas flow","Try new","Find tribe"]],
    ["Pisces","Water · Neptune/Jupiter. Romantic and imaginative.",["Trust gut","Create art","Face reality"]]
  ],
  poems: [
    ["The swift river carries a thousand-li voyage in a day.","Momentum propels you forward; things move fast, bright path ahead."],
    ["Climb to the peak, and all mountains look small.","See the big picture; current troubles are just a narrow view."],
    ["Beyond mountains and rivers, unexpectedly a village appears.","In every dead end hides a fresh turn; go around and light appears."],
    ["Ride the long wind and break waves when the time comes.","Wait for timing; prepare quietly, then set sail."],
    ["Do not worry about lonely roads; who in the world does not know you?","Treat others with heart; friends await everywhere."],
    ["Thousands of sails pass the sunken ship; ten thousand trees bloom by the sick tree.","The old falls away, new life surges; fortune turns."],
    ["To see a thousand miles, climb one more floor.","There is more ahead than meets the eye; keep climbing."],
    ["Sow one grain in spring, harvest ten thousand in autumn.","Effort returns; what you plant now fills the barn later."],
    ["If kindred souls are within the sea, the far horizon is next door.","Where the heart goes, distance melts; people and deals connect."],
    ["Heaven gave me talent, it must be used; spend a thousand gold, it comes back.","Your skill is needed now; confidence is wealth."]
  ],
  dailyAdvice: ["Move today, action beats waiting","Hold the base, expand later","Support online, trade information","Stay low, plan tomorrow big"],
  tarotMinor: [
    ["Wands","Ace of Wands","A spark of passion and new initiative.",["Great start","Creative surge","Go for it"]],
    ["Wands","Two of Wands","Planning the world, choosing a direction.",["Big vision","Decide where","Scope out"]],
    ["Wands","Three of Wands","Ships arriving, expansion ahead.",["Growth waiting","Partnerships","Look far"]],
    ["Wands","Four of Wands","Celebration, home, harmony.",["Good news","Celebrate","Foundation joy"]],
    ["Wands","Five of Wands","Scramble, healthy competition.",["Rivals sharp","Play fair","Test skills"]],
    ["Wands","Six of Wands","Victory and recognition.",["Win visible","Public praise","Receive it"]],
    ["Wands","Seven of Wands","Hold your ground.",["Defend lane","Stand firm","Stay sharp"]],
    ["Wands","Eight of Wands","Fast news, quick moves.",["Speed good","Say yes fast","Strike now"]],
    ["Wands","Nine of Wands","Resilience, final push.",["Almost there","Guard health","One more"]],
    ["Wands","Ten of Wands","Burden, carrying too much.",["Delegate","Trim load","Finish then rest"]],
    ["Wands","Page of Wands","Enthusiasm and a fresh spark.",["Start small","Follow fire","Begin!"]],
    ["Wands","Knight of Wands","Bold action, adventure.",["Move boldly","Travel luck","Seize now"]],
    ["Wands","Queen of Wands","Confident, magnetic, warm.",["Own it","Attract allies","Shine warm"]],
    ["Wands","King of Wands","Visionary leader with drive.",["Lead the charge","Set the vision","Inspire team"]],
    ["Swords","Ace of Swords","A breakthrough of truth and clarity.",["Cut through","Clear thought","Take the truth"]],
    ["Swords","Two of Swords","Stalemate, indecision.",["Decide soon","Weigh once","Enough"]],
    ["Swords","Three of Swords","Heartbreak, painful truth.",["Grieve then mend","Clear air","Let it heal"]],
    ["Swords","Four of Swords","Rest, recovery, pause.",["Take rest","Recharge","Peace first"]],
    ["Swords","Five of Swords","Win at cost, friction.",["Pick battles","Let small go","Look bigger"]],
    ["Swords","Six of Swords","Moving to calmer waters.",["Transition","Leave burden","Smooth moving"]],
    ["Swords","Seven of Swords","Deception, strategy.",["Watch backs","Ask twice","Verify"]],
    ["Swords","Eight of Swords","Feeling trapped, self-limits.",["See the door","Unbind mind","Ask help"]],
    ["Swords","Nine of Swords","Anxiety, night worry.",["Talk it out","Breathe","Worry is not fact"]],
    ["Swords","Ten of Swords","Rock bottom, end of a run.",["Surrender old","Fresh start","Rise again"]],
    ["Swords","Page of Swords","Curiosity, sharp watch.",["Ask learn","Stay alert","New info"]],
    ["Swords","Knight of Swords","Charging ahead, blunt truth.",["Act quick","Mind words","One direction"]],
    ["Swords","Queen of Swords","Clear-eyed, independent.",["Set boundaries","Facts matter","Stand clear"]],
    ["Swords","King of Swords","Authority of logic.",["Lead with mind","Be fair","Rule clearly"]],
    ["Cups","Ace of Cups","A full heart, new feelings.",["Love opens","Share warmth","Receive love"]],
    ["Cups","Two of Cups","Union, mutual bond.",["Meet halfway","Partnership","Heart talks"]],
    ["Cups","Three of Cups","Friendship, celebration.",["Gather team","Toast wins","Joy shared"]],
    ["Cups","Four of Cups","Discontent, missed offering.",["Notice gifts","Change view","Accept now"]],
    ["Cups","Five of Cups","Focus on loss, one cup left.",["Grief passes","See what remains","Reframe"]],
    ["Cups","Six of Cups","Nostalgia, old warmth.",["Revisit roots","Gentle memory","Reconnect"]],
    ["Cups","Seven of Cups","Daydreams, many choices.",["Pick one","See clearly","Avoid fantasy"]],
    ["Cups","Eight of Cups","Walking away to seek more.",["Leave comfort","Higher call","Move quiet"]],
    ["Cups","Nine of Cups","Wish fulfilled, contentment.",["Blessing shown","Enjoy it","Be grateful"]],
    ["Cups","Ten of Cups","Harmony, full-hearted family.",["Happy home","Whole picture","Love wins"]],
    ["Cups","Page of Cups","Sweet message, creative spark.",["Gentle news","New feeling","Offer care"]],
    ["Cups","Knight of Cups","Romantic pursuit, grace.",["Chase with heart","Say the sweet","Move gracefully"]],
    ["Cups","Queen of Cups","Compassionate, intuitive heart.",["Trust empathy","Nurture","Hear others"]],
    ["Cups","King of Cups","Emotional maturity, calm depth.",["Lead calmly","Feel then act","Steady heart"]],
    ["Pentacles","Ace of Pentacles","A seed of wealth and opportunity.",["Money seed","Solid start","Plant well"]],
    ["Pentacles","Two of Pentacles","Juggling priorities with ease.",["Balance acts","Flexible flow","Keep rhythm"]],
    ["Pentacles","Three of Pentacles","Mastery and teamwork.",["Show craft","Learn together","Quality seen"]],
    ["Pentacles","Four of Pentacles","Holding tight, security.",["Guard funds","Loosen grip","Stability first"]],
    ["Pentacles","Five of Pentacles","Hardship, feeling left out.",["Ask support","Warm shelter","Season passes"]],
    ["Pentacles","Six of Pentacles","Giving and receiving.",["Share fairly","Balance help","Grace flows"]],
    ["Pentacles","Seven of Pentacles","Patience, delayed harvest.",["Keep working","Trust timing","Prune small"]],
    ["Pentacles","Eight of Pentacles","Craftsmanship, practice.",["Hone skill","Detail wins","Apprentice"]],
    ["Pentacles","Nine of Pentacles","Self-made comfort, luxury.",["Enjoy harvest","Independent shine","Beautiful result"]],
    ["Pentacles","Ten of Pentacles","Legacy, lasting wealth.",["Family gain","Long view","Build legacy"]],
    ["Pentacles","Page of Pentacles","Learning the value of effort.",["Study money","Practical step","Begin small"]],
    ["Pentacles","Knight of Pentacles","Steady slogger, dependable.",["Keep pace","Reliable wins","Slow is fine"]],
    ["Pentacles","Queen of Pentacles","Nurturing provider, grounded.",["Manage well","Cozy wealth","Care + craft"]],
    ["Pentacles","King of Pentacles","Prosperity and mastery of money.",["Wealth grows","Lead with value","Build empire"]]
  ],
  liuyaoHex: [
    ["The Creative","Heaven above Heaven","Ultimate creative power, strong and pure.",["Great project","Steady rise","Lead boldly"]],
    ["The Receptive","Earth above Earth","Receptive, yielding, great nurturing.",["Follow support","Stay open","Yield and win"]],
    ["Difficulty at the Beginning","Water above Thunder","Gathering strength at the start.",["Take it stepwise","Water slowly ground","Young shoots"]],
    ["Youthful Folly","Mountain above Water","Inexperience seeks guidance.",["Ask a mentor","Learn humbly","Clean start"]],
    ["Waiting","Water above Heaven","Patience before motion.",["Wait calm","Timing comes","Prepare well"]],
    ["Conflict","Heaven above Water","Dispute, careful words.",["Stay factual","Avoid courts","Speak softly"]],
    ["The Army","Earth above Water","Discipline, mobilization.",["Organize well","Team up","Strategy wins"]],
    ["Holding Together","Water above Earth","Union and fellowship.",["Together firm","Circulate care","Unite"]],
    ["Small Accumulating","Wind above Heaven","Gentle gathering of strength.",["Small steps","Build quietly","Then leap"]],
    ["Treading","Heaven above Lake","Careful step, manners over might.",["Tread lightly","Respect rules","Diplomacy first"]],
    ["Peace","Earth above Heaven","Heaven and earth in harmony.",["Patch of calm","Good phase","Stabilize"]],
    ["Standstill","Heaven above Earth","Stagnation between forces.",["Conserve energy","Cut losses","Prepare turn"]],
    ["Fellowship","Heaven above Fire","What is alike joins.",["Find kindred","Common cause","Open fire"]],
    ["Great Possession","Fire above Heaven","Great harvest and honor.",["Steward wealth","Share credit","Shine bright"]],
    ["Modesty","Earth above Mountain","Humility beneath strength.",["Stay modest","Listen more","Power quiet"]],
    ["Enthusiasm","Thunder above Earth","Joyous movement, crowds rise.",["Stir action","Invite play","Momentum"]],
    ["Following","Lake above Thunder","Adapting, following the flow.",["Go with change","Fold gently","Learn the beat"]],
    ["Work on the Decayed","Mountain above Wind","Repairing what was spoiled.",["Fix old mess","Renew systems","Clean slate"]],
    ["Approach","Earth above Lake","Overseeing growth, nearing good.",["Good phase","Nurture rise","Move closer"]],
    ["Contemplation","Wind above Earth","Watching, perspective.",["Observe first","Read signs","Then act"]],
    ["Biting Through","Fire above Thunder","Clear the obstacle with law.",["Decisive cut","Fair judgment","Clear block"]],
    ["Grace","Mountain above Fire","Adornment, beauty.",["Polish look","Charm matters","Beauty lifts"]],
    ["Splitting Apart","Mountain above Earth","Wearing down, peel away.",["Let old peel","Small losses","Rebuild core"]],
    ["Return","Earth above Thunder","The turning point back.",["Return soon","Renew path","Recovery begins"]],
    ["Without Falsehood","Heaven above Thunder","Innocence, integrity.",["Stay true","No overreach","Purity wins"]],
    ["Great Accumulating","Mountain above Heaven","Storing strength for a big leap.",["Build reserve","Train deeply","Then break"]],
    ["Nourishment","Mountain above Thunder","Feeding body and spirit.",["Eat well","Study wise","Sustain"]],
    ["Great Exceeding","Lake above Wind","Great strain, cross the ridge.",["Press carefully","Extra care","Big load"]],
    ["The Abysmal","Water above Water","Water over water, dangerous depths.",["Move steady","Know limits","Repetition"]],
    ["The Clinging","Fire above Fire","Clinging light, inner flame.",["Stay focused","Center bright","Hold truth"]],
    ["Influence","Lake above Mountain","Mutual attraction, charm.",["Magnet pull","Careful sway","Soft bond"]],
    ["Duration","Thunder above Wind","Long-lasting movement.",["Stay constant","Keep pace","Enduring"]],
    ["Retreat","Heaven above Mountain","Timely withdrawal.",["Step back","Preserve strength","Re-enter later"]],
    ["Great Power","Thunder above Heaven","Mighty advance, strength.",["Break through","Bold force","Righteous power"]],
    ["Progress","Fire above Earth","Sun rising, advancing.",["Move up","Clear aim","Steady climb"]],
    ["Darkening of the Light","Earth above Fire","Light hidden, hardship.",["Keep inner light","Hill the time","Protect soul"]],
    ["The Family","Wind above Fire","Household harmony.",["Family care","Calm leadership","Nurture ties"]],
    ["Opposition","Fire above Lake","Divergence, contrast.",["Find common","Respect diff","Align later"]],
    ["Obstruction","Water above Mountain","Hazard ahead, slow advance.",["Pause and plan","Ask way","Climb careful"]],
    ["Deliverance","Thunder above Water","Freeing, easing strain.",["Release held","Move again","Storm passing"]],
    ["Decrease","Mountain above Lake","Reducing for value.",["Cut waste","Simplify","Quality above"]],
    ["Increase","Wind above Thunder","Gaining, abundance rising.",["Good to give","Harvest point","Grow right"]],
    ["Breakthrough","Lake above Heaven","Resolute action, resolve.",["Decide firmly","Cut the cord","Press on"]],
    ["Coming to Meet","Heaven above Wind","Encounter, sudden meeting.",["Meet openly","Unexpected path","Be receptive"]],
    ["Gathering Together","Lake above Earth","Coming together, assembly.",["Gather allies","Shared purpose","Community"]],
    ["Pushing Upward","Earth above Wind","Rising through merit.",["Climb worthy","Steady growth","Help upskill"]],
    ["Oppression","Lake above Water","Exhaustion, constraint.",["Endure dark","Speak less","Wait release"]],
    ["The Well","Water above Wind","Nourishing source for all.",["Share source","Maintain well","Community water"]],
    ["Revolution","Lake above Fire","Transformation, renewal.",["Change fully","Old mold breaks","Fresh season"]],
    ["The Cauldron","Fire above Wind","Cultivation, new vessel.",["Cook new","Transform raw","Warm growth"]],
    ["The Arousing","Thunder above Thunder","Shock that stirs action.",["Respond swift","Shake awake","Adjust fast"]],
    ["Keeping Still","Mountain above Mountain","Standing still, inner calm.",["Hold steady","Stillness heals","Wait"]],
    ["Development","Wind above Mountain","Gradual progress.",["Step gradual","Feather grow","Patience"]],
    ["The Marrying Maiden","Thunder above Lake","Odd union, careful bond.",["Align values","Mind contract","Fit is key"]],
    ["Abundance","Thunder above Fire","Fullness, great brightness.",["Bountiful now","Celebrate","Share the light"]],
    ["The Wanderer","Fire above Mountain","Traveler, moving light.",["Stay adaptable","Pack light","New lands"]],
    ["The Gentle","Wind above Wind","Gentle penetration.",["Go soft","Persist through","Comply to pass"]],
    ["The Joyous","Lake above Lake","Open-hearted joy.",["Share mirth","Speak glad","Welcome play"]],
    ["Dispersion","Wind above Water","Scattering, dissolving barriers.",["Release old","Flow apart","Let go"]],
    ["Limitation","Water above Lake","Setting beneficial limits.",["Bound what matters","Conserve","Clear edge"]],
    ["Inner Truth","Wind above Lake","Sincerity moves hearts.",["Be honest","Trust builds","Speak true"]],
    ["Small Overpass","Thunder above Mountain","Careful small steps over obstacle.",["Mind details","Small wins","Clear passage"]],
    ["After Completion","Water above Fire","Order achieved, stay vigilant.",["Guard success","Sustain balance","Watch drift"]],
    ["Before Completion","Fire above Water","Almost complete, cautious crossing.",["Nearly there","Avoid rush","Finish right"]]
  ],
  qimenGates: [
    ["Open Gate","New doors open; career and public matters go well.",["New job luck","Public deeds","Appointments"]],
    ["Rest Gate","Easier to rest now; a pause calms the nerves.",["Take a break","Healing","Privacy"]],
    ["Life Gate","Fortune favors you; trade and joy thrive.",["Good deals","Pleasure","Trade"]],
    ["Hurt Gate","Rivalry and shocks; go steady, avoid fights.",["Watch rivals","Drive safe","Slow pace"]],
    ["Block Gate","Withdraw and guard; advance carefully.",["Stay low","Review plans","Secure assets"]],
    ["Scenery Gate","Fame and show; beauty catches eyes.",["Showcase","Design","Public image"]],
    ["Death Gate","Endings and sudden loss; seek a new direction.",["Old cycles end","Let go","Beware extremes"]],
    ["Shock Gate","Nerves and talk; move with alertness.",["Caution","Keep calm","Facts first"]]
  ],
  faces: [
    ["Forehead","Broad full forehead: early luck and intelligence."],
    ["Eyes","Bright clear eyes: honesty and sharp insight."],
    ["Nose","Full nose: wealth and drive."],
    ["Cheeks","Rounded cheeks: support and popularity."],
    ["Mouth","Kind mouth: good talk and soft fate."],
    ["Chin","Strong chin: endurance and stable later years."]
  ],
  palmLines: [
    ["Life Line","Wraps the thumb; vitality and health.",["Clear curve: strong energy","Long: stamina","Short: intense bursts"]],
    ["Head Line","Runs mid-palm; mind and career.",["Straight: logical","Slope: creative","Clear: focus"]],
    ["Heart Line","Top line; love and feelings.",["Deep: warm heart","Broken: guarded heart","Faint: cool head"]],
    ["Fate Line","Vertical center; life direction.",["Clear: clear path","Weak: self-made","Wavy: flexible"]],
    ["Sun Line","Toward the ring finger; fame.",["Long: public favor","Short: quiet talent","Split: dual talents"]],
    ["Health Line","Waist close; vitality.",["Faint: fine","Deep: rest more","Beaded: watch health"]],
    ["Marriage Line","Under little finger; unions.",["Clear: clear bond","Broken: changes","Curved: drama"]]
  ],
  dreamIcons: [
    ["Water","Emotions and money flowing.",["Wealth drifts in","Emotion refresh","Opportunity tide"]],
    ["Fire","Passion and action.",["Passion peaks","Act now","Watch temper"]],
    ["Snake","Change and hidden wisdom.",["Transformation","Hidden insight","Be alert"]],
    ["Dragon","Great luck and rising power.",["Big win near","Authority grows","Seize the moment"]],
    ["Flying","Breakthrough and freedom.",["Sky's the limit","New heights","Release worry"]],
    ["Falling","Anxiety and needed landing.",["Slow down","Face it","Support near"]],
    ["Teeth","Stress about looks or words.",["Clear words","Let worry go","Say it"]],
    ["Chased","Pushed by a pressure.",["Face the issue","Reduce load","Stand strong"]],
    ["Pregnancy","A new thing is growing.",["Project coming","Nurture it","Prepare"]],
    ["Exam","Being tested.",["Self-check","Knowledge pays","Trust prep"]],
    ["Gold","Value and feeling lucky.",["Money chance","Value grows","Stay honest"]],
    ["Dead relative","A tie being released.",["Let go softly","Family karma","Peace"]]
  ],
  numerology: [
    ["1","Independent","Strong-willed path"],["2","Cooperative","Team energy"],["3","Expressive","Creative voice"],
    ["4","Steady","Discipline builds"],["5","Freedom","Change and travel"],["6","Care","Harmony and duty"],
    ["7","Wisdom","Depth and research"],["8","Power","Authority and wealth"],["9","Completion","Big heart"],
    ["0","Void","Hollow beginnings"],["11","Master Teacher","High insight"],["22","Master Builder","Large-scale dream"]
  ],
  guanyinSigns: [
    ["First","Hermit's gate opens; patience brings the answer."],
    ["Second","Water gains; steady flow sweetens."],
    ["Third","Stone turns; effort meets reward."],
    ["Fourth","Old friend returns; what you seek comes back."],
    ["Fifth","Dawn breaks; hope rises."],
    ["Sixth","Moon nears; wishes ripen."],
    ["Seventh","Sun behind clouds; wait a little."],
    ["Eighth","Phoenix soars; big news arrives."],
    ["Ninth","Path bends; a detour still arrives."],
    ["Tenth","Harvest ready; claim what is yours."]
  ],
  names: { logo:"Shen Suan Ge", slogan:"AI Fortune · Mysteries Solved · From $4" },
  ziweiStars: [
    ["Zi Wei","The Imperial Star. Monarch energy, backbone of the chart.",["Leadership calling","Chose your own path","Magnificent but lonely"]],
    ["Tian Fu","The Treasury Star. Wealth keeper, steady abundance.",["Saving power","Steady wealth","Comfort above all"]],
    ["Tai Yang","The Sun Star. Bright fame, generous, promotes others.",["Public shine","Help rise","Achieve in light"]],
    ["Wu Qu","The Military Star. Driving force, executes plans.",["Act strong","Execute now","Strength in life"]],
    ["Tian Ji","The Magician Star. Quick wit, strategy in motion.",["Move fast","Change plans","Mind wins"]],
    ["Tai Yin","The Moon Star. Gentle wealth, patience and care.",["Soft power","Nurture others","Inner light"]],
    ["Tan Lang","The Greedy Wolf Star. Charm, desire, ambition.",["Charisma high","Desire pushes","Watch excess"]],
    ["Ju Men","The Giant Gate Star. Debate, influence over others.",["Words move","Loud opinions","Persuade"]],
    ["Tian Xiang","The Prime Minister Star. Grace, diplomacy, support.",["Speak well","Serve well","Stay gracious"]],
    ["Tian Liang","The Sunbeam Star. Protection, solving problems.",["Help others","Shield up","Mediator"]],
    ["Qi Sha","The Seven Kills Star. Rush, decisive power.",["Direct moves","Sharp knife","Careful edge"]],
    ["Po Jun","The Breaker Star. Reform, overturning the old.",["Break old","Rebuild bold","Shake it up"]],
    ["Lian Zhen","The Integrity Star. Talent mixed with emotion.",["Skill + feeling","Beware love mess","Refine"]]
  ]
};
window.DSEN = true;